source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb') if File.exist?(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'))
  # Se o seu projeto usa a estrutura padrão recente do Flutter, use a linha abaixo:
  # load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end