name: Conserlar Build Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS and Android
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          cache: true

      - name: Clean Pub Cache and Get Dependencies
        run: |
          flutter pub cache clean -f
          flutter pub get

      - name: Forçar iOS 16 em todos os arquivos do projeto
        run: |
          find ios -name "*.pbxproj" -o -name "*.xcconfig" | xargs sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g'
          plutil -replace MinimumOSVersion -string "16.0" ios/Runner/Info.plist || true

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS App (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios/iphoneos/*.app

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/*.apk