name: Build iOS Simulator

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS for Simulator (No Codesign)
        run: flutter build ios --simulator --debug --no-codesign